### ISSUE TITLE
Rstudio crashing on some networks caused by tomatrix() function in fixedrow()

### ISSUE THREAD

**Issue by Alex7722** [domagal9/backbone#36]
I have used a particular function with multiple networks and it was working fine. However, with some of the networks in my list Rstudio is crashing in the tomatrix() part of fixedrow(). I can't find the reason why. Reproducible example:

```
require(igraph)
require(tidygraph)
require(backbone)

bipartite_graph <- readRDS("backbone_debug_network.RDS")
bipartite_graph <- as.igraph(bipartite_graph)
fixedrow(bipartite_graph, class = "igraph")
```

[backbone_debug_network.zip](https://github.com/zpneal/backbone/files/8547436/backbone_debug_network.zip)

**Comment by zpneal** [comment]
Using igraph 1.3.1, I get the following error message:

```
Warning message:
In get.incidence.dense(graph, types = types, names = names, attr = attr) :
  At core/misc/bipartite.c:757 : 2 edges running within partitions were ignored.
```

I think this indicates that although your `bipartite_graph` is claimed to be bipartite, it really isn't. I'm not familiar with tidygraph objects, so I'm not sure how to manually verify, but this is a temporary workaround:

```
require(igraph)
require(tidygraph)
require(backbone)
bipartite_graph <- readRDS("backbone_debug_network.RDS")
bipartite_graph <- as.igraph(bipartite_graph)
incidence <- as_incidence_matrix(bipartite_graph)  #Get the incidence matrix first; displays error
bb <- fixedrow(incidence, class = "igraph")  #Run fixedrow() on the matrix
```

This works, but use it with caution since the backbone is being extracted from data that is probably slightly different from what's contained in `backbone_debug_network.RDS`. Something is getting lost in the `as_incidence_matrix()` function.

**Comment by Alex7722** [comment]
Indeed, my mistake was that the column "types" was named "type".  Still Tidygraph managed to identify it as a bipartite, not sure how. Your warning message clued me in.
The weird thing is that I used this function on a list of networks with the same variable names, but only a few were a problem.

Fix:
`bipartite_graph <- bipartite_graph %>% activate(nodes) %>% mutate(types=type)`

Thank you !

**Comment by zpneal** [comment]
I'm glad you were able to find the issue...and that it turned out to be something minor. Thanks for sharing the fix!
